version: "3"

services:
  restapi:
    build:
      context:  .
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - restapi
    ports:
      - "8080:8080"